const actions = {
    login: "LOGIN",
    signUp: "SIGN_UP", 
    getMyProfile: "GET_MY_PROFILE",
    editProfile: "EDIT_PROFILE",
    addEArt: "ADDEART",
    addGallery: "ADDGALLERY",
    getGalleries: "GETGALLERY",
    getOwnedEarts: "GETOWNEDEARTS",
    uploadProfileImage: "UPLOADPROFILEIMAGE",
    editEart: "EDITEART",
    getEart: "GETEART",
    postForSale: "POSTFORSALE",
    unlistEart: "UNLIST",
    getAllEarts: "GETALLEARTS",
    createEdition: "CREATEEDITION",
    getEartEditions: "GETEARTEDITIONS",
    changeOwner: "CHANGEOWNER",
    createCopyEart: "CREATECOPYEART",
    getCopyEarts: "GETCOPYEARTS",
    getCopyEart: "GETCOPYEART",
    getUserGalleries: "GETUSERGALLERIES",
    getUserOwnedArts: "GETUSEROWNEDARTS",
    getGalleryEarts: "GETGALLERYEARTS",
    changePrivacy: "CHANGEPRIVACY",
    uploadGalleryImage: "UPLOADGALLERYIMAGE",
    getUserProfile: "GETUSERPROFILE",
    getUserCopyEarts: "GETUSERCOPYEARTS"
}

export default actions